services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    drupol\sncbdelay_twitter\:
        resource: '../../*'
        exclude: '../../{Entity,Migrations,Tests}'

    sncbdelay_twitter.twitter:
        class: Abraham\TwitterOAuth\TwitterOAuth
        arguments: ["@=container.getParameter('twitter')['consumer_key']", "@=container.getParameter('twitter')['consumer_secret']", "@=container.getParameter('twitter')['access_token']", "@=container.getParameter('twitter')['access_token_secret']"]
        public: true

    sncbdelay_twitter.brevity:
        class: Kylewm\Brevity\Brevity
        public: true

    drupol\sncbdelay_twitter\EventSubscriber\Twitter\Alert:
        arguments: ['@service_container', '@twig', '@logger', '@cache.app', '@doctrine.orm.entity_manager']

    drupol\sncbdelay_twitter\EventSubscriber\Twitter\Delay:
        arguments: ['@service_container', '@twig', '@logger', '@cache.app', '@doctrine.orm.entity_manager']

    drupol\sncbdelay_twitter\EventSubscriber\Twitter\Canceled:
        arguments: ['@service_container', '@twig', '@logger', '@cache.app', '@doctrine.orm.entity_manager']

    drupol\sncbdelay_twitter\EventSubscriber\Twitter\Custom:
        arguments: ['@service_container', '@twig', '@logger', '@cache.app', '@doctrine.orm.entity_manager']
